---
title: "ST558 Project 1"
author: "David Arthur"
date: "6/14/2021"
output:
  github_document:
    toc: true
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(httr)
library(jsonlite)
library(knitr)
library(DT)
```

# Function to get Team ID when name is input
```{r}
franchiseInfo <- GET("https://records.nhl.com/site/api/franchise") %>% 
  content("text") %>% 
  fromJSON(flatten = TRUE)

teamNameIdMatch <- franchiseInfo$data %>% select(id, mostRecentTeamId, fullName)

getTeamId <- function(team){
  Id <- teamNameIdMatch %>% filter(str_detect(fullName, team)) %>%
    select(id)
  if (nrow(Id) == 1){
    return(as.numeric(Id))
  } else {
    stop("try again entering team name or ID")
  }
}
```

## Records API functions
```{r}
recordsBaseURL <- "https://records.nhl.com/site/api"

getFranchiseInfo <- function(team = NULL){
  if(is.null(team)){
    fullURL <- paste0(recordsBaseURL, "/franchise")
    franchiseInfo <- GET(fullURL) %>%
      content("text") %>%
      fromJSON(flatten = TRUE)
  } else{
    if(!is.numeric(team)){team <- getTeamId(team)}
    fullURL <- paste0(recordsBaseURL, "/franchise?cayenneExp=id=", team)
    franchiseInfo <- GET(fullURL) %>%
      content("text") %>%
      fromJSON(flatten = TRUE)
  }
  return(franchiseInfo$data)
}

getTeamTotals <- function(team = NULL){
  if(is.null(team)){
    fullURL <- paste0(recordsBaseURL, "/franchise-team-totals")
    teamTotals <- GET(fullURL) %>%
      content("text") %>%
      fromJSON(flatten = TRUE)
  } else{
    if(!is.numeric(team)){team <- getTeamId(team)}
    fullURL <- paste0(recordsBaseURL, "/franchise-team-totals?cayenneExp=franchiseId=", team)
    teamTotals <- GET(fullURL) %>%
      content("text") %>%
      fromJSON(flatten = TRUE)
  }
  return(teamTotals$data)
}

getSeasonRecords <- function(team = NULL){
  if(is.null(team)){
    fullURL <- paste0(recordsBaseURL, "/franchise-season-records")
    seasonRecords <- GET(fullURL) %>%
      content("text") %>%
      fromJSON(flatten = TRUE)
  } else{
  if(!is.numeric(team)){team <- getTeamId(team)}
  fullURL <- paste0(recordsBaseURL, "/franchise-season-records?cayenneExp=franchiseId=", team)
  seasonRecords <- GET(fullURL) %>% content("text") %>% fromJSON(flatten = TRUE)
  }
  return(seasonRecords$data)
}

getGoalieRecords <- function(team = NULL){
  if(is.null(team)){
    fullURL <- paste0(recordsBaseURL, "/franchise-goalie-records")
    goalieRecords <- GET(fullURL) %>%
      content("text") %>%
      fromJSON(flatten = TRUE)
  } else{
  if(!is.numeric(team)){team <- getTeamId(team)}
  fullURL <- paste0(recordsBaseURL, "/franchise-goalie-records?cayenneExp=franchiseId=", team)
  goalieRecords <- GET(fullURL) %>% content("text") %>% fromJSON(flatten = TRUE)
  }
  return(goalieRecords$data)
}

getSkaterRecords<- function(team = NULL){
  if(is.null(team)){
    fullURL <- paste0(recordsBaseURL, "/franchise-skater-records")
    skaterRecords <- GET(fullURL) %>%
      content("text") %>%
      fromJSON(flatten = TRUE)
  } else{
  if(!is.numeric(team)){team <- getTeamId(team)}
  fullURL <- paste0(recordsBaseURL, "/franchise-skater-records?cayenneExp=franchiseId=", team)
  skaterRecords <- GET(fullURL) %>% content("text") %>% fromJSON(flatten = TRUE)
  }
  return(skaterRecords$data)
}

getFranchiseDetail <- function(team = NULL){
  if(is.null(team)){
    fullURL <- paste0(recordsBaseURL, "/franchise-detail")
    franchiseDetail <- GET(fullURL) %>%
      content("text") %>%
      fromJSON(flatten = TRUE)
  } else{
  if(!is.numeric(team)){team <- getTeamId(team)}
  fullURL <- paste0(recordsBaseURL, "/franchise-detail?cayenneExp=id=", team)
  franchiseDetail <- GET(fullURL) %>% content("text") %>% fromJSON(flatten = TRUE)
  }
  return(franchiseDetail$data)
}

franchiseInfo <- getFranchiseInfo()
franchiseInfo %>% filter(is.na(lastSeasonId))
kable(getFranchiseInfo("Hurricanes"))
kable(getTeamTotals())
datatable(getTeamTotals())
activeTeams <- teamTotals %>% filter(activeFranchise == 1) %>% select(teamName) %>% distinct()
datatable(getTeamTotals("Hurricanes"))
getSeasonRecords()
getSeasonRecords("Carolina")
getGoalieRecords()
getGoalieRecords("Hurricanes")
getSkaterRecords()
getSkaterRecords(26)
datatable(getFranchiseDetail())
getFranchiseDetail("Canadiens")$generalManagerHistory

```


##Stats API function
fix name id match
```{r Stats API}
getTeamIdStats <- function(team){
  Id <- teamNameIdMatch %>% filter(str_detect(fullName, team)) %>%
    select(mostRecentTeamId)
  if (nrow(Id) == 1){
    return(as.numeric(Id))
  } else {
    stop("try again entering team name or ID")
  }
}

getStats <- function(team = NULL){
  if(is.null(team)){
    teamStats <- GET("https://statsapi.web.nhl.com/api/v1/teams?expand=team.stats") %>%
    content("text") %>%
    fromJSON(flatten = TRUE) %>%
    as.data.frame()
    allTeams <- data.frame()
    for (i in seq_along(teamStats$teams.id)){
      allTeams <- bind_rows(allTeams, teamStats[[9]][[i]][[1]][[1]])
    }
    allTeams <- allTeams %>% relocate(starts_with("team"))
    return(allTeams)
  } else{
    if(!is.numeric(team)) {team <- getTeamIdStats(team)}
    fullURL <- paste0("https://statsapi.web.nhl.com/api/v1/teams", "/", team, "?expand=team.stats")
    teamStats <- GET(fullURL) %>%
      content("text") %>%
      fromJSON(flatten = TRUE) %>%
      as.data.frame()
    oneTeam <- teamStats[[9]][[1]][[1]][[1]] %>%
      relocate(starts_with("team"))
    return(oneTeam)
  }
}


stats <- getStats()
activeStats <- stats %>% select(team.name) %>% rename(teamName = team.name) %>% distinct
setdiff(activeTeams, activeStats)
teamTotals %>% filter(teamName %in% as_vector(setdiff(activeTeams, activeStats))) %>% select(teamName) %>% n_distinct()

getStats("Devils")

#for stats without rankings
#str(testStats2[[9]][[11]][[1]][[1]][1,]) %>%
#  relocate(starts_with("team"))
```

## Wrapper function
```{r}
getChoice <- function(what, team = NULL){
  switch(what,
         franchise = getFranchiseInfo(team),
         totals = getTeamTotals(team),
         season = getSeasonRecords(team),
         goalie = getGoalieRecords(team),
         skater = getSkaterRecords(team),
         detail = getFranchiseDetail(team),
         stats = getStats(team),
         stop("try again entering what you want")
         )
}

getChoice("franchise", 26)
getChoice("totals")
getChoice("season", "Caro")
getChoice("goalie", "Rangers")
getChoice("skater", "Philadelphia Q")
getChoice("detail")
getChoice("stats", "Detroit")

```

## EDA
```{r}
getChoice("detail")
```

